Shopify/checkout-sheet-kit-android

- lib/src/main/java/com/shopify/checkoutkit/CheckoutEventProcessor.kt
- lib/src/main/java/com/shopify/checkoutkit/LogWrapper.kt
- lib/src/test/java/com/shopify/checkoutkit/DefaultCheckoutEventProcessorTest.kt
Updates DefaultCheckoutEventProcessor
1. Replaces the println() call with a `Log.w()` call
2. Adds tests 
3. Adds a LogWrapper to allow asserting on log messages
> add tests for default checkout event processor

- CHANGELOG.md
- lib/build.gradle
- lib/src/main/java/com/shopify/checkoutkit/CheckoutEventProcessor.kt
- lib/src/test/java/com/shopify/checkoutkit/DefaultCheckoutEventProcessorTest.kt
Expose the errorDescription var on the CheckoutException class
> Expose the errorDescription var on the CheckoutException class

- lib/src/main/java/com/shopify/checkoutkit/CheckoutBridge.kt
- lib/src/main/java/com/shopify/checkoutkit/CheckoutWebView.kt
- lib/src/test/java/com/shopify/checkoutkit/CheckoutBridgeSdkEventsTest.kt
Adds instrumentation events from sdk->web. Focus is on adding the core eventing system now, only adding one metric for the moment
- [] I have updated any documentation related to these changes.
> add instrumentation events to checkout bridge

- lib/src/main/java/com/shopify/checkoutsheetkit/Configuration.kt
- lib/src/test/java/com/shopify/checkoutsheetkit/CheckoutDialogTest.kt
> enable preloading by default

- lib/src/main/java/com/shopify/checkoutsheetkit/CheckoutDialog.kt
Ensure that the webview is scrolled to top when the loading spinner is dismissed. N.B. this will not work with the sticky pay button.
> Ensure webview isn't scrolled down on open

- lib/src/main/java/com/shopify/checkoutsheetkit/pixelevents/PixelEvent.kt
- lib/src/main/java/com/shopify/checkoutsheetkit/pixelevents/PixelEventDecoder.kt
Remove non-checkout pixel events.
> remove pixel events that dont apply to checkout

- lib/src/main/java/com/shopify/checkoutsheetkit/CheckoutDialog.kt
Remove this scroll fix now that a fix has been applied in checkout
> remove scroll now that a fix has been applied in checkout

- lib/src/main/res/layout/dialog_checkout.xml
Update the header horizontal whitespace to match those in checkout
> match header horizontal padding with checkout

- lib/src/main/java/com/shopify/checkoutsheetkit/CheckoutWebView.kt
- lib/src/main/java/com/shopify/checkoutsheetkit/ShopifyCheckoutSheetKit.kt
- lib/src/test/java/com/shopify/checkoutsheetkit/CheckoutWebViewClientTest.kt
- lib/src/test/java/com/shopify/checkoutsheetkit/CheckoutWebViewTest.kt
Allow differentiating between preloads and normal loads on the backend by sending a prefetch header for preloaded checkouts.
> send prefetch header for preloaded checkouts

- lib/src/main/java/com/shopify/checkoutsheetkit/pixelevents/PixelEvent.kt
- lib/src/main/java/com/shopify/checkoutsheetkit/pixelevents/PixelEventDecoder.kt
- lib/src/test/java/com/shopify/checkoutsheetkit/CheckoutBridgeTest.kt
- lib/src/test/java/com/shopify/checkoutsheetkit/InteropTest.java
- lib/src/test/java/com/shopify/checkoutsheetkit/pixelevents/PixelEventDecoderTest.kt
- samples/MobileBuyIntegration/app/src/main/java/com/shopify/checkout_sdk_mobile_buy_integration_sample/common/analytics/Analytics.kt
- samples/MobileBuyIntegration/app/src/main/java/com/shopify/checkout_sdk_mobile_buy_integration_sample/common/navigation/CheckoutSdkNavHost.kt
Use a single StandardPixelEvent data class now that the supported events all have the same shape
> simplify pixel types

- README.md
Fixes outdated interface name appearing in README, and recommends extending `DefaultCheckoutEventProcessor`
> Update readme details around the checkout event processor

- README.md
- samples/MobileBuyIntegration/app/src/main/res/values/strings.xml
Add details to the README on how to set a customized/localized Dialog title.
> Add section to README on customizing the dialog title

- lib/src/main/java/com/shopify/checkoutsheetkit/CheckoutWebView.kt
The docs say `Some older WebView implementations require additionalHttpHeaders to be mutable.`
https://developer.android.com/reference/android/webkit/WebView#loadUrl(java.lang.String,%20java.util.Map%3Cjava.lang.String,java.lang.String%3E)
So, updating additional headers to be a mutable map
> Use mutable map for additional headers

- lib/src/main/java/com/shopify/checkoutsheetkit/CheckoutWebView.kt
- lib/src/main/java/com/shopify/checkoutsheetkit/CheckoutWebViewContainer.kt
- lib/src/main/java/com/shopify/checkoutsheetkit/CheckoutWebViewEventProcessor.kt
- lib/src/test/java/com/shopify/checkoutsheetkit/CheckoutWebViewCacheTest.kt
Alternative approach to https://github.com/Shopify/checkout-sheet-kit-android/pull/72
Mark the cache as stale on complete, so that it's discarded on next present.
> Mark cache entry as stale on checkout completed

- CHANGELOG.md
- README.md
- lib/build.gradle
- lib/src/main/java/com/shopify/checkoutsheetkit/lifecycleevents/CheckoutCompletedEventDecoder.kt
- lib/src/test/java/com/shopify/checkoutsheetkit/CheckoutCompletedEventDecoderTest.kt
- samples/MobileBuyIntegration/app/build.gradle
increment version numbers and update changelog for v2
Make orderDetails non-null on onCheckoutCompleted
> increment version numbers and update changelog for v2

- CHANGELOG.md
- lib/build.gradle
- lib/src/main/java/com/shopify/checkoutsheetkit/BaseWebView.kt
- lib/src/main/java/com/shopify/checkoutsheetkit/CheckoutBridge.kt
- lib/src/main/java/com/shopify/checkoutsheetkit/CheckoutWebView.kt
- lib/src/main/java/com/shopify/checkoutsheetkit/FallbackWebView.kt
- lib/src/test/java/com/shopify/checkoutsheetkit/CheckoutBridgeTest.kt
- lib/src/test/java/com/shopify/checkoutsheetkit/CheckoutWebViewTest.kt
- lib/src/test/java/com/shopify/checkoutsheetkit/FallbackWebViewTest.kt
- Refactor how user agents are set a little to allow for a little code reuse (e.g. around version number and `ShopifyCheckoutSdk`).
- Set version to 3.0.0-beta.1
- Strip the beta part off when setting the UA
> refactor user agent setting, set beta release version

- lib/src/main/java/com/shopify/checkoutsheetkit/ShopifyCheckoutSheetKit.kt
Have the possibility to dismiss the `CheckoutDialog` once the checkout is completed. 
At the moment this is not possible since we don't have the instance of the dialog created so we can't call `dismiss` on it.
With this PR the `CheckoutDialog` reference is returned so it can be used later to dismiss it.
> The present function returns the Dialog so it can be dismissed at a later time

- scripts/check_license_headers.rb
use File.readlines instead of IO.readlines in our check license headers script
> use File.readlines instead of IO.readlines

- CHANGELOG.md
- README.md
- lib/build.gradle
- lib/src/main/java/com/shopify/checkoutsheetkit/BaseWebView.kt
- lib/src/main/java/com/shopify/checkoutsheetkit/CheckoutEventProcessor.kt
- lib/src/main/java/com/shopify/checkoutsheetkit/CheckoutWebViewEventProcessor.kt
- lib/src/test/java/com/shopify/checkoutsheetkit/CheckoutDialogTest.kt
- lib/src/test/java/com/shopify/checkoutsheetkit/CheckoutWebViewTest.kt
- lib/src/test/java/com/shopify/checkoutsheetkit/FallbackWebViewTest.kt
- samples/MobileBuyIntegration/app/build.gradle
- samples/MobileBuyIntegration/app/src/main/AndroidManifest.xml
- samples/MobileBuyIntegration/app/src/main/java/com/shopify/checkout_sdk_mobile_buy_integration_sample/common/MobileBuyEventProcessor.kt
- samples/MobileBuyIntegration/app/src/main/java/com/shopify/checkout_sdk_mobile_buy_integration_sample/common/navigation/CheckoutSdkNavHost.kt
- samples/MobileBuyIntegration/app/src/main/java/com/shopify/checkout_sdk_mobile_buy_integration_sample/common/permissions/Permissions.kt
adds an `onPermissionRequest()` function to the CheckoutEventProcessor interface, to allow clients to grants permissions to camera/audio/other. This is required by some 3rd party apps to perform actions like verifying identity. 
See https://github.com/Shopify/checkout-sheet-kit-android/issues/113
Open a web page that requires camera access via the sample app.  Ensure the camera can be accessed.
> [!IMPORTANT]
>
> - [ ] I've updated the …
> Add onPermissionRequest to allow clients to camera permissions for verification apps

- .github/pull_request_template.md
- CHANGELOG.md
- README.md
- lib/build.gradle
- lib/src/main/java/com/shopify/checkoutsheetkit/pixelevents/PixelEvent.kt
- lib/src/test/java/com/shopify/checkoutsheetkit/CheckoutWebViewTest.kt
- lib/src/test/java/com/shopify/checkoutsheetkit/FallbackWebViewTest.kt
Update the web-pixel data classes to reflect the latest schema and bump the version.
Also updates the PR template to add one more Todo r.e. incrementing the library version
You can complete a checkout and check the logs section of the sample app (hamburger in settings)
> [!IMPORTANT]
>
---
<details>
<summary>Checklist for releasing a new …
> Update data classes to reflect latest web pixel schema

- CHANGELOG.md
- README.md
- lib/build.gradle
- lib/src/main/java/com/shopify/checkoutsheetkit/BaseWebView.kt
- lib/src/main/java/com/shopify/checkoutsheetkit/CheckoutDialog.kt
- lib/src/main/java/com/shopify/checkoutsheetkit/CheckoutWebViewContainer.kt
- lib/src/test/java/com/shopify/checkoutsheetkit/CheckoutWebViewContainerTest.kt
- lib/src/test/java/com/shopify/checkoutsheetkit/CheckoutWebViewTest.kt
CLOSES https://github.com/Shopify/checkout-sheet-kit-android/issues/127
When preloading is enabled and we fetch the checkout web view from the cache, there are some scenarios where we try to add the fetched view to a parent container when it already has a parent (causing an IllegalStateException).
This can be reproduced by enabling preloading, then calling `present()` twice without dismissing the modal (there also may be other cases).
This PR looks to ensure the webView has no existing parent before we add it to its container.
---
Note: When we remove checkout web views from their container, we also look to ensure it's destroyed if we think it will not be used again, to avoid memory leaks. We don't want to do this destroy/cleanup in this case, as the view will be added to the view …
> Ensure no existing parent is present before adding to container

- CHANGELOG.md
- README.md
- lib/build.gradle
- lib/src/main/java/com/shopify/checkoutsheetkit/CheckoutDialog.kt
- lib/src/main/java/com/shopify/checkoutsheetkit/CheckoutWebView.kt
- lib/src/main/java/com/shopify/checkoutsheetkit/UriExtensions.kt
- lib/src/test/java/com/shopify/checkoutsheetkit/CheckoutDialogTest.kt
Recovery reloads the provided checkout URL in a simplified WebView. This is incompatible with single-use multipass URLs.
This PR prevents entering the recovery flow for multipass URLs.
Open a multipass checkout
Force an error
Ensure checkout does not try to recover 
> [!IMPORTANT]
>
---
<details>
<summary>Checklist for releasing a new …
> Disable recovery flow for multipass urls

- CHANGELOG.md
- README.md
- lib/src/main/java/com/shopify/checkoutsheetkit/ShopifyCheckoutSheetKit.kt
- lib/src/test/java/com/shopify/checkoutsheetkit/CheckoutWebViewContainerTest.kt
- lib/src/test/java/com/shopify/checkoutsheetkit/ShopifyCheckoutSheetKitTest.kt
- samples/MobileBuyIntegration/app/src/main/java/com/shopify/checkout_sdk_mobile_buy_integration_sample/cart/CartItem.kt
- samples/MobileBuyIntegration/app/src/main/java/com/shopify/checkout_sdk_mobile_buy_integration_sample/cart/CartState.kt
- samples/MobileBuyIntegration/app/src/main/java/com/shopify/checkout_sdk_mobile_buy_integration_sample/cart/CartView.kt
- samples/MobileBuyIntegration/app/src/main/java/com/shopify/checkout_sdk_mobile_buy_integration_sample/cart/CartViewModel.kt
- samples/MobileBuyIntegration/app/src/main/java/com/shopify/checkout_sdk_mobile_buy_integration_sample/common/client/StorefrontClient.kt
- samples/MobileBuyIntegration/app/src/main/java/com/shopify/checkout_sdk_mobile_buy_integration_sample/product/ProductView.kt
Exposes an invalidate function that clients can call to invalidate the preload cache.
Adds quantity controls to the cart page in the MobileBuyIntegration sample app.  Calls invalidate when they're used.
https://github.com/user-attachments/assets/1d679d96-d462-4779-bf0c-3dfcf473ad85
Start it up and test it out
> [!IMPORTANT]
>
---
<details> …
> Add cart quantity controls and expose preload cache invalidate function

- CHANGELOG.md
- README.md
- lib/src/main/java/com/shopify/checkoutsheetkit/CheckoutEventProcessor.kt
- lib/src/main/java/com/shopify/checkoutsheetkit/CheckoutWebView.kt
- lib/src/main/java/com/shopify/checkoutsheetkit/UriExtensions.kt
- lib/src/test/java/com/shopify/checkoutsheetkit/CheckoutWebViewClientTest.kt
- lib/src/test/java/com/shopify/checkoutsheetkit/DefaultCheckoutEventProcessorTest.kt
- samples/MobileBuyIntegration/app/src/main/AndroidManifest.xml
Open deep links externally, similar to ios here - https://github.com/Shopify/checkout-sheet-kit-swift/pull/227
- When links are clicked, we'll call `onCheckoutLinkClicked()`
- The DefaultCheckoutEventProcessor will try to open the link
- The client app should specified `queries` in its manifest to determine which links/schemes should open.
Tested with a couple of links
```html
<a href="geo:40.712776,-74.005974?q=Statue+of+Liberty">
Statue of Liberty
</a>
<a href="sms:+1234567890?body=Hello%20there!">
Send SMS
</a>
```
https://github.com/user-attachments/assets/41375d89-3d20-4c18-aa30-b922e5e266de
> [!IMPORTANT]
>
> - [x] I have read and agree with the [Contribution Guidelines](https://github.com/shopify/checkout-sheet-kit-android/blob/m …
> Open deep links externally

- lib/src/main/java/com/shopify/checkoutsheetkit/CheckoutWebView.kt
- lib/src/main/java/com/shopify/checkoutsheetkit/UriExtensions.kt
- lib/src/test/java/com/shopify/checkoutsheetkit/CheckoutWebViewClientTest.kt
Prevent calling onCheckoutLinkClicked() for the about scheme, e.g. about:blank
n/a
> [!IMPORTANT]
>
---
<details>
</details>
> [!TIP]
> See the [Contributing documentation](https://github.com/shopify/checkout-sheet-kit-android/blob/main/.github/CONTRIBUTING.md#releasing-a-new-version) for …
> Ignore about scheme

- samples/MobileBuyIntegration/app/build.gradle
- samples/MobileBuyIntegration/app/src/main/java/com/shopify/checkout_sdk_mobile_buy_integration_sample/common/MoneyFormatter.kt
- samples/MobileBuyIntegration/app/src/main/java/com/shopify/checkout_sdk_mobile_buy_integration_sample/common/client/ProductPagingSource.kt
- samples/MobileBuyIntegration/app/src/main/java/com/shopify/checkout_sdk_mobile_buy_integration_sample/common/client/StorefrontClient.kt
- samples/MobileBuyIntegration/app/src/main/java/com/shopify/checkout_sdk_mobile_buy_integration_sample/common/components/TextComponents.kt
- samples/MobileBuyIntegration/app/src/main/java/com/shopify/checkout_sdk_mobile_buy_integration_sample/common/navigation/BottomAppBarWithNavigation.kt
- samples/MobileBuyIntegration/app/src/main/java/com/shopify/checkout_sdk_mobile_buy_integration_sample/di/AppModule.kt
- samples/MobileBuyIntegration/app/src/main/java/com/shopify/checkout_sdk_mobile_buy_integration_sample/logs/LogOverview.kt
- samples/MobileBuyIntegration/app/src/main/java/com/shopify/checkout_sdk_mobile_buy_integration_sample/logs/LogOverviewHeader.kt
- samples/MobileBuyIntegration/app/src/main/java/com/shopify/checkout_sdk_mobile_buy_integration_sample/logs/LogsView.kt
- samples/MobileBuyIntegration/app/src/main/java/com/shopify/checkout_sdk_mobile_buy_integration_sample/products/ProductsView.kt
- samples/MobileBuyIntegration/app/src/main/java/com/shopify/checkout_sdk_mobile_buy_integration_sample/products/ProductsViewModel.kt
- samples/MobileBuyIntegration/app/src/main/java/com/shopify/checkout_sdk_mobile_buy_integration_sample/products/product/AddToCartButton.kt
- samples/MobileBuyIntegration/app/src/main/res/values/strings.xml
Adds pagination on the products view, for stores with a large number of products
Adds a basic in-memory graphQL query cache to prevent repeatedly making requests for the same data on page nav
Run it against the checkout-sdk store.
Network inspector can be used for checking requests, but we also log when we fetch and return cached entries.
Pagination also logs when it's making requests
> [!IMPORTANT]
>
> - [ ] I've updated the …
> Implement product paging and add query cache

- CHANGELOG.md
- README.md
- lib/build.gradle
- lib/src/main/java/com/shopify/checkoutsheetkit/BaseWebView.kt
- lib/src/main/java/com/shopify/checkoutsheetkit/CheckoutEventProcessor.kt
- lib/src/main/java/com/shopify/checkoutsheetkit/CheckoutWebViewEventProcessor.kt
- lib/src/test/java/com/shopify/checkoutsheetkit/CheckoutWebViewTest.kt
- samples/MobileBuyIntegration/app/src/main/AndroidManifest.xml
- samples/MobileBuyIntegration/app/src/main/java/com/shopify/checkout_sdk_mobile_buy_integration_sample/MainActivity.kt
- samples/MobileBuyIntegration/app/src/main/java/com/shopify/checkout_sdk_mobile_buy_integration_sample/common/MobileBuyEventProcessor.kt
Allow clients to implement onGeolocationPermissionsShowPrompt() for dealing with use my location in the pickup points part of checkout (if enabled).
Recorded an example here:
https://github.com/user-attachments/assets/44abc899-fc40-4da3-8cb6-17868c54c7f3
N.b. it says no locations found
> [!IMPORTANT]
>
---
<details>
<summary>Checklist for releasing …
> Allow clients to handle onGeolocationPermissionsShowPrompt() calls

- samples/SimpleCheckout/.env.example
- samples/SimpleCheckout/app/build.gradle
Small tweak to take the Storefront API version from the environment, with a default value
- Add a println("apiVersion $apiVersion") to the app/build.gradle
- Set no value for STOREFRONT_API_VERSION in .env
- ./gradlew compileDebugKotlin
- check printed value is 2024-10
- Update value for STOREFRONT_API_VERSION to 2024-07
- ./gradlew compileDebugKotlin
- check printed value is 2024-07
> [!IMPORTANT]
>
> - [x ] I have read and agree with the [Contribution Guidelines](https://github.com/shopify/checkout-sheet-kit-android/blob/main/.github/CONTRIBUTING.md).
> - [ ] I've updated the …
> Take api version from the environment

- samples/MobileBuyIntegration/app/src/main/java/com/shopify/checkout_sdk_mobile_buy_integration_sample/cart/CartItem.kt
- samples/MobileBuyIntegration/app/src/main/java/com/shopify/checkout_sdk_mobile_buy_integration_sample/cart/data/CartState.kt
- samples/MobileBuyIntegration/app/src/main/java/com/shopify/checkout_sdk_mobile_buy_integration_sample/cart/data/ModelMappingExt.kt
- samples/MobileBuyIntegration/app/src/main/java/com/shopify/checkout_sdk_mobile_buy_integration_sample/cart/data/source/network/CartStorefrontApiClient.kt
- samples/MobileBuyIntegration/app/src/main/java/com/shopify/checkout_sdk_mobile_buy_integration_sample/common/ui/theme/Theme.kt
- samples/MobileBuyIntegration/app/src/main/java/com/shopify/checkout_sdk_mobile_buy_integration_sample/products/collection/ProductCollectionProduct.kt
- samples/MobileBuyIntegration/app/src/main/java/com/shopify/checkout_sdk_mobile_buy_integration_sample/products/product/AddToCartButton.kt
- samples/MobileBuyIntegration/app/src/main/java/com/shopify/checkout_sdk_mobile_buy_integration_sample/products/product/OptionSelector.kt
- samples/MobileBuyIntegration/app/src/main/java/com/shopify/checkout_sdk_mobile_buy_integration_sample/products/product/ProductView.kt
- samples/MobileBuyIntegration/app/src/main/java/com/shopify/checkout_sdk_mobile_buy_integration_sample/products/product/ProductViewModel.kt
- samples/MobileBuyIntegration/app/src/main/java/com/shopify/checkout_sdk_mobile_buy_integration_sample/products/product/data/ModelMappingExt.kt
- samples/MobileBuyIntegration/app/src/main/java/com/shopify/checkout_sdk_mobile_buy_integration_sample/products/product/data/Product.kt
- samples/MobileBuyIntegration/app/src/main/java/com/shopify/checkout_sdk_mobile_buy_integration_sample/products/product/data/ProductRepository.kt
- samples/MobileBuyIntegration/app/src/main/java/com/shopify/checkout_sdk_mobile_buy_integration_sample/products/product/data/source/network/ProductsStorefrontApiClient.kt
- samples/MobileBuyIntegration/app/src/main/java/com/shopify/checkout_sdk_mobile_buy_integration_sample/settings/SettingsView.kt
- samples/MobileBuyIntegration/app/src/main/java/com/shopify/checkout_sdk_mobile_buy_integration_sample/settings/SettingsViewModel.kt
Allow selecting different variant options, respect available for sale
I've added variants to the cat palm product in the checkout store for testing
https://github.com/user-attachments/assets/b40c5189-299a-43bd-8f7a-31d1ab9767a8
> [!IMPORTANT]
>
---
<details>
</details>
> [!TIP]
> See the …
> Allow selecting different variant options, respect available for sale

- lib/build.gradle
- lib/src/main/AndroidManifest.xml
- lib/src/main/java/com/shopify/checkoutsheetkit/BaseWebView.kt
This change enables the [Payment Request API for WebView](https://developers.chrome.com/docs/android/payments-in-webviews). This is a requirement for [Google Pay to work](https://developers.google.com/pay/api/android/guides/recipes/using-android-webview) within the WebView the Checkout Sheet Kit uses.
For more details see #92 
https://github.com/user-attachments/assets/9de37aac-c682-4d6a-b137-ff4d90d7ed10
---
> [!IMPORTANT]
>
> - [ ] …
> enabling payment request for WebView

- lib/src/main/java/com/shopify/checkoutsheetkit/Configuration.kt
- lib/src/test/java/com/shopify/checkoutsheetkit/DefaultCheckoutEventProcessorTest.kt
- lib/src/test/java/com/shopify/checkoutsheetkit/Helpers.kt
- samples/MobileBuyIntegration/app/build.gradle
- samples/MobileBuyIntegration/app/src/main/java/com/shopify/checkout_sdk_mobile_buy_integration_sample/CheckoutSdkApp.kt
- samples/MobileBuyIntegration/app/src/main/java/com/shopify/checkout_sdk_mobile_buy_integration_sample/cart/CartView.kt
- samples/MobileBuyIntegration/app/src/main/java/com/shopify/checkout_sdk_mobile_buy_integration_sample/cart/data/source/network/CartStorefrontApiClient.kt
- samples/MobileBuyIntegration/app/src/main/java/com/shopify/checkout_sdk_mobile_buy_integration_sample/common/components/MoneyText.kt
- samples/MobileBuyIntegration/app/src/main/java/com/shopify/checkout_sdk_mobile_buy_integration_sample/common/di/AppModule.kt
- samples/MobileBuyIntegration/app/src/main/java/com/shopify/checkout_sdk_mobile_buy_integration_sample/settings/ColorSchemeSection.kt
- samples/MobileBuyIntegration/app/src/main/java/com/shopify/checkout_sdk_mobile_buy_integration_sample/settings/authentication/data/source/local/CustomerAccessTokenStore.kt
- samples/MobileBuyIntegration/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
- samples/MobileBuyIntegration/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
- samples/MobileBuyIntegration/build.gradle
- samples/SimpleCheckout/app/build.gradle
- samples/SimpleCheckout/build.gradle
Update a number of sample app dependencies in one go
N.B. This brings some sample app versions ahead of the lib (e.g. kotlin & kotlinx serialization versions), which is fine. We can keep some versions in the lib a little lower to ensure better compatibility with various clients.
N.B.2: Encrypted shared prefs is deprecated. So we've switched it out.
N.B.3: Timber was previously depended on transitively though mobile buy, we now explicitly depend on it in the Mobile Buy sample (not the lib)
Click around in the sample apps
> [!IMPORTANT]
>
> - [x] I have read and agree with the [Code of …
> Sample app dependency bump

- .github/workflows/publish.yml
Now that the repository was renamed, we need to update the task to match
running `./gradlew tasks`
We see output:
```
publishReleasePublicationToMavenLocal - Publishes Maven publication 'release' to the local Maven repository.
publishReleasePublicationToOssrh-staging-apiRepository - Publishes Maven publication 'release' to Maven repository 'ossrh-staging-api'.
```
So, I've taken the task name from there.
Try to run the publish job
> [!IMPORTANT]
>
> - [x] I have read and agree with the [Code of Conduct](https://github.com/shopify/checkout-sheet-kit-android/blob/main/.github/CODE_OF_CO …
> Update task now that we have renamed the repository

- README.md
- lib/build.gradle
- lib/src/main/java/com/shopify/checkoutsheetkit/CheckoutBridge.kt
- lib/src/main/java/com/shopify/checkoutsheetkit/CheckoutWebViewEventProcessor.kt
- lib/src/main/java/com/shopify/checkoutsheetkit/ThreadExtensions.kt
- lib/src/test/java/com/shopify/checkoutsheetkit/ThreadExtensionsTest.kt
We've received a couple of reports around errors being observed when receiving events:
`Methods marked with @UiThread must be executed on the main thread. Current thread: JavaBridge. Calling onCheckoutFailedWithError`
This was because `CheckoutBridge.postMessage()` (called from the JavaScript bridge on the "JavaBridge" thread) was directly calling event processor methods in some cases.
As a solution:
- Created ThreadExtensions.kt with a reusable onMainThread() utility function
- Updated CheckoutBridge to wrap all event processor calls with onMainThread {}
- Refactored CheckoutWebViewEventProcessor to use the shared utility instead of duplicate code
The onMainThread() function:
- Executes immediately if already on the main thread (no performance impact for main thread usage)
- Posts to …
> Emit events from the main thread

- README.md
- lib/build.gradle
- lib/src/main/java/com/shopify/checkoutsheetkit/BaseWebView.kt
- lib/src/main/java/com/shopify/checkoutsheetkit/CheckoutException.kt
- lib/src/test/java/com/shopify/checkoutsheetkit/CheckoutWebViewClientTest.kt
Removes references to checkout.liquid which has since been deprecated.
---
> [!IMPORTANT]
>
---
<details>
</details>
> [!TIP]
> See the [Contributing documentation](https://github.com/shopify/checkout-sheet-kit-android/blob/main/.github/CONTRIBUTING.md#releasing-a-new-version) for …
> Remove outdated liquid reference
