Shopify/checkout-sheet-kit-android

- .github/CODEOWNERS
- README.md
- Update readme
- Add CODEOWNERS file
> Add hero image to README.md

- .github/workflows/check_license_headers.yml
- .github/workflows/cla.yml
- .github/workflows/publish.yml
- .github/workflows/test.yml
Update the runners used for github action workflows
> update github action runners

- README.md
> Remove readme references to web pixels until finalised

- .github/workflows/publish.yml
- README.md
Small docs tweak for pixel events.  
Also a missed github action version upgrade.
> update pixel docs

- lib/src/main/java/com/shopify/checkoutsheetkit/lifecycleevents/CompletedEvent.kt
Sort event attributes to make it easier to compare across repos.
> Sort event attributes

- samples/MobileBuyIntegration/app/build.gradle
- samples/MobileBuyIntegration/build.gradle
- samples/SimpleCheckout/app/build.gradle
- samples/SimpleCheckout/build.gradle
- samples/SimpleCheckout/gradle.properties
- samples/SimpleCheckout/gradle/wrapper/gradle-wrapper.properties
Bump a number of sample app dependencies
> update sample app dependencies

- CHANGELOG.md
- README.md
- lib/build.gradle
- samples/MobileBuyIntegration/app/build.gradle
Increment version numbers and update changelog
> update changelog and versions

- samples/MobileBuyIntegration/app/build.gradle
- samples/MobileBuyIntegration/build.gradle
Upgrade a few dependencies / plugins
> bump dependencies

- lib/build.gradle
- lib/src/main/java/com/shopify/checkoutsheetkit/BaseWebView.kt
- lib/src/main/java/com/shopify/checkoutsheetkit/Configuration.kt
- lib/src/test/java/com/shopify/checkoutsheetkit/CheckoutDialogTest.kt
- lib/src/test/java/com/shopify/checkoutsheetkit/CheckoutWebViewTest.kt
- lib/src/test/java/com/shopify/checkoutsheetkit/FallbackWebViewTest.kt
- lib/src/test/java/com/shopify/checkoutsheetkit/InteropTest.java
Allows us to better identify requests coming from ReactNative.
> Adds a "Platform" property to the ShopifyCheckoutSheetKit configuration for identifying other platforms.

- .github/ISSUE_TEMPLATE/bug_report.yml
> Minor improvements to bug template

- CHANGELOG.md
- README.md
- lib/build.gradle
- lib/src/test/java/com/shopify/checkoutsheetkit/errors/CheckoutErrorDecoderTest.kt
> release 3.0.0

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
Add a feature request template to the repo
> Add feature request template

- .gitignore
- lib/build.gradle
- lib/proguard-rules.pro
- samples/MobileBuyIntegration/app/proguard-rules.pro
Implements consumer proguard rules to prevent minifying CSK classes.
---
> [!IMPORTANT]
>
> - [ ] I have bumped the version number in the [`build.gradle` file](https://github.com/Shopify/checkout-kit-android/blob/main/lib/build.gradle#L17)
> - [ ] I have added a [Changelog](https://github.com/shopify/checkout-sheet-kit-android/blob/main/CHANGELOG.md …
> Implement keepclasses proguard consumer rules

- README.md
> [readme] Create table of contents

- .vscode/extensions.json
- README.md
> Add vscode recommendations + fix hierarchy

- samples/MobileBuyIntegration/app/src/main/AndroidManifest.xml
When the soft keyboard is visible, it can hide the new customer accounts email input.
Add `android:windowSoftInputMode="adjustResize"` 
`to ensure that the system resizes your layout to the available space—which keeps all of your layout content accessible, even if it requires scrolling` https://developer.android.com/develop/ui/views/touch-and-input/keyboard-input/visibility#Respond
| Before| After |
|--|--|
|![Screenshot 2025-04-23 at 10 00 23](https://github.com/user-attachments/assets/389802c8-8156-430e-a2d2-54d046d5a35e)|![Screenshot 2025-04-23 at 10 01 26](https://github.com/user-attachments/assets/62b5db61-e1a6-4b9f-99a8-09c826c7f1a0)|
N.B. there are also some auto-formatting changes in here which can be ignored
n/a
> [!IMPORTANT]
>
> - [ ] I've added tests to support my …
> Set windowSoftInputMode for Customer Account login

- lib/build.gradle
Update library test dependency versions
run `./gradlew build`
> [!IMPORTANT]
>
---
<details>
</details>
> [!TIP]
> See the [Contributing documentation](https://github.com/shopify/checkout-sheet-kit-android/blob/main/.github/CONTRIBUTING.md#releasing-a-new-version) for instructions on how to …
> update library test dependencies

- lib/build.gradle
Context:
https://central.sonatype.org/publish/publish-portal-ossrh-staging-api/
n/a
> [!IMPORTANT]
>
---
<details>
</details>
> [!TIP]
> See the [Contributing documentation](https://github.com/shopify/checkout-sheet-kit-android/blob/main/.github/CONTRIBUTING.md#releasing-a-new-version) for …
> Use OSSRH staging API

- .github/workflows/publish.yml
Some background here:
https://central.sonatype.org/publish/publish-portal-ossrh-staging-api/#post-to-manualuploadrepositoryrepository-key
We previously logged in to oss.sonatype.org to close and release staged releases. To continue with that workflow, we need a couple of new API calls.
I've run these locally for the current release to figure out what's needed. This PR aims to automate that 
N.b. the code is untested, we might need some tweaks during the next release.
Complete the next release
> [!IMPORTANT]
>
> - [x] I have read and agree with the [Code of …
> Update publish workflow to upload repository

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- samples/MobileBuyIntegration/build.gradle
- samples/MobileBuyIntegration/gradle/wrapper/gradle-wrapper.properties
- samples/SimpleCheckout/build.gradle
- samples/SimpleCheckout/gradle/wrapper/gradle-wrapper.properties
Combines the various AGP dependabot updates into one
Probably just a run through Checkout
> [!IMPORTANT]
>
---
<details>
</details>
> [!TIP]
> See the [Contributing documentation](https://github.com/shopify/checkout-sheet-kit-android/blob/main/.github/CONTRIBUTING.md#releasing-a-new-version) …
> Update AGP from 8.11.0 to 8.11.1
